CREATE TABLE eav_attribute(
	attribute_id SMALLINT(5) AUTO_INCREMENT PRIMARY KEY,
	entity_type_id SMALLINT(5) NOT NULL,
	attribute_code VARCHAR(255) NOT NULL,
	attribute_model VARCHAR(255) NULL,
	backend_model VARCHAR(255) NULL,
	backend_type ENUM('STATIC','DATETIME','DECIMAL','INT','TEXT','VARCHAR') NOT NULL,
	backend_table VARCHAR(255) NULL,
	fontend_model VARCHAR(255) NULL,
	fontend_input VARCHAR(50) NULL,
	fontend_input_renderer VARCHAR(255) NULL,
	fonted_label VARCHAR(255) NULL,
	fontend_class VARCHAR(255) NULL,
	source_model VARCHAR(255) NULL,
	is_global TINYINT(1) NOT NULL,
	is_visible TINYINT(1) NOT NULL,
	is_required TINYINT(1) NOT NULL,
	is_user_defined TINYINT(1) NOT NULL,
	default_value TEXT NULL,
	is_searchable TINYINT(1) NOT NULL,
	is_filterable TINYINT(1) NOT NULL,
	is_comparable TINYINT(1) NOT NULL,
	is_visible_on_font TINYINT(1) NOT NULL,
	is_html_allowed_on_font TINYINT(1) NOT NULL,
	is_unique TINYINT(1) NOT NULL,
	is_used_for_price_rules TINYINT(1) NOT NULL,
	is_filterable_in_search TINYINT(1) NOT NULL,
	used_in_product_listing TINYINT(1) NOT NULL,
	used_for_sort_by TINYINT(1) NOT NULL,
	is_configurable TINYINT(1) NOT NULL,
	apply_to VARCHAR(255) NOT NULL,
	position INT(11) NOT NULL,
	note VARCHAR(255) NOT NULL,
	is_visible_in_advanced_search TINYINT(1) NOT NULL
)
